name = "SpatialIndexing"
uuid = "d4ead438-fe20-5cc5-a293-4fd39a41b74c"
author = "Alexey Stukalov"
version = "0.1.5"

[compat]
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
